[package]
name = "helicase"
version = "0.1.0"
authors = ["Boomber <boomberisalreadytaken@gmail.com>"]
edition = "2018"

build = "src/build.rs"

[build-dependencies]
lalrpop = { version="0.18.1", features = ["lexer"]}

[dependencies]
regex = "1.3.5"
lalrpop-util = "0.18.1"