name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        rust: ["stable", "beta", "nightly"]
    name: Check ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  test:
     runs-on: [ubuntu-latest, windows-latest, macos-latest]
     strategy:
       matrix:
         rust: ["stable", "beta", "nightly"]
     name: Test Suite ${{ matrix.rust }}
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: ${{ matrix.rust }}
           override: true
       - uses: actions-rs/cargo@v1
         with:
           command: test
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        rust: ["stable", "beta", "nightly"]
    name: Build ${{ matrix.rust }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
  
